spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Filmotheque;encrypt=false
    username: sa
    password: Pa$$w0rd
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.SQLServerDialect